version: '3.8'

services:
  processor:
    build: ./MP4Processor
    container_name: processor
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - /tmp:/tmp  # NOTE: The processor needs to access to files on filesystem
      - /tmp/outputs # NOTE: The processor needs to access to files on filesystem
    depends_on:
      - nats

  nodejs:
    build: ./app
    container_name: app
    environment:
      - NATS_URL=nats://nats:4222
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=box
      - DB_PASSWORD=box
      - DB_NAME=box
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - nats
      - processor

  nats:
    image: nats:2.9.22
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --http_port 8222

  postgres:
    image: postgres
    container_name: box
    environment:
      POSTGRES_USER: box
      POSTGRES_PASSWORD: box
      POSTGRES_DB: box
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
